"""add is_saved to trips

Revision ID: 3cc7d3293f0f
Revises: 133602c79113
Create Date: 2026-08-14 00:07:29.107388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""add is_saved to trips

Revision ID: 3cc7d3293f0f
Revises: 133602c79113
Create Date: 2026-08-14 00:07:29.107388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cc7d3293f0f'
down_revision: Union[str, None] = '133602c79113'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('is_saved', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'is_saved')
    # ### end Alembic commands ###
