"""Add is_saved to Trip

Revision ID: aa1309c66973
Revises: 133602c79113
Create Date: 2026-08-13 20:25:39.080529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""Add is_saved to Trip

Revision ID: aa1309c66973
Revises: 133602c79113
Create Date: 2026-08-13 20:25:39.080529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa1309c66973'
down_revision: Union[str, None] = '133602c79113'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('is_saved', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'is_saved')
    # ### end Alembic commands ###
